format_strings = true
format_macro_matchers = true
imports_layout = "HorizontalVertical"
merge_imports = true
match_block_trailing_comma = true
merge_derives = true
newline_style = "Unix"
normalize_comments = true
reorder_impl_items = true
space_after_colon = true
space_before_colon = false
struct_lit_single_line = false
type_punctuation_density = "Wide"
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
